AllCops:
  RunRailsCops: true
  Exclude:
    - bin/**/*
    - config/boot.rb
    - db/schema.rb
    - script/**/*
    - tmp/**/*
    - vendor/**/*

# １クラスの行数を200行以下に制限する
Metrics/ClassLength:
  Max: 200

# １行の文字数を制限しない
Metrics/LineLength:
  Enabled: false

# １メソッドの行数を制限しない
Metrics/MethodLength:
  Enabled: false

# 日本語コメントを許す
Style/AsciiComments:
  Enabled: false

# ファイル冒頭にコメントを書かなくてもよい
Style/Documentation:
  Enabled: false

# class Hoge::Fooのような記述を許す
Style/ClassAndModuleChildren:
  Enabled: false
